server:
  port: 8080

spring:
  application:
    name : springboot-cli

eureka:
  client:
   service-url:
    defaultZone : http://localhost:8081/eureka/

#ribbon:
#  ReadTimeout: 12000
#  ConnectTioneout: 3000
